Vagrant.configure("2") do |config|
  ## Choose your base box
  config.vm.box = "hashicorp/precise32"

  ## For masterless, mount your salt file root
  config.vm.synced_folder "salt/roots/", "/srv/salt/"

  ## Use all the defaults:
  config.vm.provision :salt do |kdsalt|

  #  salt.minion_config = "salt/minion"
    #salt.run_highstate = true

  end

  config.vm.provision :shell, path: "bootstrap.sh"
end
